//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.DataAcessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrievanceDetail
    {
        public long GrievanceDetailsId { get; set; }
        public long GrievanceId { get; set; }
        public string Details { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual GrievanceMaster GrievanceMaster { get; set; }
    }
}
