//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.DataAcessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrievanceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrievanceMaster()
        {
            this.GrievanceDetails = new HashSet<GrievanceDetail>();
        }
    
        public long GrievanceId { get; set; }
        public string GrievanceNumber { get; set; }
        public int UserId { get; set; }
        public short StatusId { get; set; }
        public short GrievanceTypeId { get; set; }
        public string Subject { get; set; }
        public short PriorityId { get; set; }
        public string AddCc { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrievanceDetail> GrievanceDetails { get; set; }
        public virtual GrievancePriorityMaster GrievancePriorityMaster { get; set; }
        public virtual GrievanceTypeMaster GrievanceTypeMaster { get; set; }
        public virtual GrievanceUserDetail GrievanceUserDetail { get; set; }
    }
}
